name: easy_drag_and_drop
description: 
  Package make easier drag and drop 
  for list of widgets

version: 0.0.1
repository: https://github.com/SonaHunanyan/easy_drag_and_drop

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

